[profile.default]
out = "out"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
src = "contracts"
libs = ["node_modules", "lib"]
test = "test"
cache_path = "cache_forge"

remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "erc4626-tests/=lib/openzeppelin-contracts-upgradeable/lib/erc4626-tests/",
    "forge-std/=lib/forge-std/src/",
    "halmos-cheatcodes/=lib/openzeppelin-contracts-upgradeable/lib/halmos-cheatcodes/src/",
    "safe-contracts/=lib/safe-contracts/",
    "@gnosis/conditional-tokens-contracts/=lib/conditional-tokens-contracts/contracts/",

]

[fuzz]
runs = 5000
max_test_rejects = 150000

[rpc_endpoints]
mainnet = "https://eth-mainnet.alchemyapi.io/v2/YOUR_ALCHEMY_KEY"
optimism_sepolia = "https://sepolia.optimism.io/"
arbitrum_one_sepolia = "https://sepolia-rollup.arbitrum.io/rpc/"
needs_undefined_env_var = "${UNDEFINED_RPC_URL_PLACEHOLDER}"
anvil = "http://127.0.0.1:8545"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "attributes_first"
quote_style = "double"
number_underscore = "preserve"
single_line_statement_blocks = "preserve"
ignore = ["src/console.sol", "src/console2.sol"]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
